const num = Number(prompt('Digite seu número!'));
const numeroTitulo = document.getElementById('numero-titulo');
const texto = document.getElementById('texto');
numeroTitulo.innerHTML = num;
texto.innerHTML = `<p>Seu número + 2 é ${num+2}</p>`
texto.innerHTML += `<p>A raiz quadrada do seu numero é ${num ** 0.5}</p>`
texto.innerHTML += `<p>${num} é inteiro?: ${Number.isInteger(num)}</p>`
texto.innerHTML += `<p>É NaN: ${Number.isNaN(num)}</p>`
texto.innerHTML += `<p>Arrendondado pra baixo: ${Math.floor(num)}</p>`
texto.innerHTML += `<p>Arrendondado pra cima: ${Math.ceil(num)}</p>`
texto.innerHTML += `<p>Com duas casas decimais: ${parseFloat(num.toFixed(2))}</p>`
